/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DesignJanelas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco.nsjunior1
 */
public class AbaEstoqueBaixo extends javax.swing.JFrame {

    /**
     * Creates new form AbaEstoqueBaixo
     */
    public AbaEstoqueBaixo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBaixoestoque = new javax.swing.JTable();
        txtCodestbaixo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtItemestbaixo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQntdestbaixo = new javax.swing.JTextField();
        btInserirestbaixo = new javax.swing.JButton();
        btExcluirestbaixo = new javax.swing.JButton();
        btAltestbaixo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque Baixo");

        tbBaixoestoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Item", "Qntd"
            }
        ));
        jScrollPane1.setViewportView(tbBaixoestoque);

        jLabel2.setText("Código");

        jLabel3.setText("Item");

        jLabel4.setText("Quantidade");

        btInserirestbaixo.setText("Inserir");
        btInserirestbaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirestbaixoActionPerformed(evt);
            }
        });

        btExcluirestbaixo.setText("Excluir");
        btExcluirestbaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirestbaixoActionPerformed(evt);
            }
        });

        btAltestbaixo.setText("Alterar");
        btAltestbaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltestbaixoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtCodestbaixo, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtItemestbaixo)
                            .addComponent(txtQntdestbaixo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btExcluirestbaixo)
                            .addComponent(btInserirestbaixo)
                            .addComponent(btAltestbaixo))
                        .addGap(12, 12, 12)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodestbaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemestbaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQntdestbaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btInserirestbaixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluirestbaixo)
                        .addGap(12, 12, 12)
                        .addComponent(btAltestbaixo)
                        .addGap(30, 30, 30))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirestbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirestbaixoActionPerformed
         if (tbBaixoestoque.getSelectedRow() != -1){
        DefaultTableModel tbProduto = (DefaultTableModel) tbBaixoestoque.getModel();
        tbProduto.removeRow(tbBaixoestoque.getSelectedRow());
         }
    }//GEN-LAST:event_btExcluirestbaixoActionPerformed

    private void btInserirestbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirestbaixoActionPerformed
         DefaultTableModel tbProduto = (DefaultTableModel) tbBaixoestoque.getModel();
        Object [] dados = {txtCodestbaixo.getText(), txtCodestbaixo.getText(), txtQntdestbaixo.getText()};
        tbProduto.addRow(dados);
    }//GEN-LAST:event_btInserirestbaixoActionPerformed

    private void btAltestbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltestbaixoActionPerformed
          if(tbBaixoestoque.getSelectedRow() != -1){
            tbBaixoestoque.setValueAt(txtCodestbaixo.getText(), tbBaixoestoque.getSelectedRow(), 0);
            tbBaixoestoque.setValueAt(txtCodestbaixo.getText(), tbBaixoestoque.getSelectedRow(), 1);
            tbBaixoestoque.setValueAt(txtQntdestbaixo.getText(), tbBaixoestoque.getSelectedRow(), 2);
          }
    }//GEN-LAST:event_btAltestbaixoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbaEstoqueBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbaEstoqueBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbaEstoqueBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbaEstoqueBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbaEstoqueBaixo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltestbaixo;
    private javax.swing.JButton btExcluirestbaixo;
    private javax.swing.JButton btInserirestbaixo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBaixoestoque;
    private javax.swing.JTextField txtCodestbaixo;
    private javax.swing.JTextField txtItemestbaixo;
    private javax.swing.JTextField txtQntdestbaixo;
    // End of variables declaration//GEN-END:variables
}
